{
 "title": "Price Whisper Monitoring Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "No. of Instances",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (new_created_by_name) (label_replace(kube_pod_info{created_by_kind=\"ReplicaSet\"}, \"new_created_by_name\", \"$1\", \"created_by_name\", \"(.*)-.*\"))\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage (%) 1m",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (instance)(\r\n  (1 - rate(node_cpu_seconds_total{mode=\"idle\", kubernetes_name=\"\"}[1m])) * 100\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage (%) over time",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "avg by (instance)(\r\n  (1 - rate(node_cpu_seconds_total{mode=\"idle\", kubernetes_name=\"\"}[1m])) * 100\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage (%) 1m",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (instance) (100 * (1 - ((avg_over_time(node_memory_MemFree_bytes{kubernetes_name=\"\"}[1m]) + avg_over_time(node_memory_Cached_bytes{kubernetes_name=\"\"}[1m]) + avg_over_time(node_memory_Buffers_bytes{kubernetes_name=\"\"}[1m])) / avg_over_time(node_memory_MemTotal_bytes{kubernetes_name=\"\"}[1m]))))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage (%) over time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "sum by (instance) (100 * (1 - ((avg_over_time(node_memory_MemFree_bytes{kubernetes_name=\"\"}[2m]) + avg_over_time(node_memory_Cached_bytes{kubernetes_name=\"\"}[2m]) + avg_over_time(node_memory_Buffers_bytes{kubernetes_name=\"\"}[2m])) / avg_over_time(node_memory_MemTotal_bytes{kubernetes_name=\"\"}[2m]))))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rx (30s) bytes/s",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "sum by (instance) (rate(node_network_receive_bytes_total{kubernetes_name=\"\",device!=\"lo\"}[30s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tx (30s) bytes/s",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "expr": "sum by (instance) (rate(node_network_transmit_bytes_total{kubernetes_name=\"\",device!=\"lo\"}[30s]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}