// Code generated by mockery v2.39.1. DO NOT EDIT.

package prices

import (
	mock "github.com/stretchr/testify/mock"
	model "hsfl.de/group6/hsfl-master-ai-cloud-engineering/product-service/prices/model"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: _a0
func (_m *MockRepository) Create(_a0 *model.Price) (*model.Price, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *model.Price
	var r1 error
	if rf, ok := ret.Get(0).(func(*model.Price) (*model.Price, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(*model.Price) *model.Price); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Price)
		}
	}

	if rf, ok := ret.Get(1).(func(*model.Price) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - _a0 *model.Price
func (_e *MockRepository_Expecter) Create(_a0 interface{}) *MockRepository_Create_Call {
	return &MockRepository_Create_Call{Call: _e.mock.On("Create", _a0)}
}

func (_c *MockRepository_Create_Call) Run(run func(_a0 *model.Price)) *MockRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*model.Price))
	})
	return _c
}

func (_c *MockRepository_Create_Call) Return(_a0 *model.Price, _a1 error) *MockRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_Create_Call) RunAndReturn(run func(*model.Price) (*model.Price, error)) *MockRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: _a0
func (_m *MockRepository) Delete(_a0 *model.Price) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*model.Price) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - _a0 *model.Price
func (_e *MockRepository_Expecter) Delete(_a0 interface{}) *MockRepository_Delete_Call {
	return &MockRepository_Delete_Call{Call: _e.mock.On("Delete", _a0)}
}

func (_c *MockRepository_Delete_Call) Run(run func(_a0 *model.Price)) *MockRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*model.Price))
	})
	return _c
}

func (_c *MockRepository_Delete_Call) Return(_a0 error) *MockRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_Delete_Call) RunAndReturn(run func(*model.Price) error) *MockRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindAll provides a mock function with given fields:
func (_m *MockRepository) FindAll() ([]*model.Price, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []*model.Price
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]*model.Price, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []*model.Price); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Price)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type MockRepository_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
func (_e *MockRepository_Expecter) FindAll() *MockRepository_FindAll_Call {
	return &MockRepository_FindAll_Call{Call: _e.mock.On("FindAll")}
}

func (_c *MockRepository_FindAll_Call) Run(run func()) *MockRepository_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRepository_FindAll_Call) Return(_a0 []*model.Price, _a1 error) *MockRepository_FindAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_FindAll_Call) RunAndReturn(run func() ([]*model.Price, error)) *MockRepository_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindAllByUser provides a mock function with given fields: userId
func (_m *MockRepository) FindAllByUser(userId uint64) ([]*model.Price, error) {
	ret := _m.Called(userId)

	if len(ret) == 0 {
		panic("no return value specified for FindAllByUser")
	}

	var r0 []*model.Price
	var r1 error
	if rf, ok := ret.Get(0).(func(uint64) ([]*model.Price, error)); ok {
		return rf(userId)
	}
	if rf, ok := ret.Get(0).(func(uint64) []*model.Price); ok {
		r0 = rf(userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Price)
		}
	}

	if rf, ok := ret.Get(1).(func(uint64) error); ok {
		r1 = rf(userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_FindAllByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAllByUser'
type MockRepository_FindAllByUser_Call struct {
	*mock.Call
}

// FindAllByUser is a helper method to define mock.On call
//   - userId uint64
func (_e *MockRepository_Expecter) FindAllByUser(userId interface{}) *MockRepository_FindAllByUser_Call {
	return &MockRepository_FindAllByUser_Call{Call: _e.mock.On("FindAllByUser", userId)}
}

func (_c *MockRepository_FindAllByUser_Call) Run(run func(userId uint64)) *MockRepository_FindAllByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint64))
	})
	return _c
}

func (_c *MockRepository_FindAllByUser_Call) Return(_a0 []*model.Price, _a1 error) *MockRepository_FindAllByUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_FindAllByUser_Call) RunAndReturn(run func(uint64) ([]*model.Price, error)) *MockRepository_FindAllByUser_Call {
	_c.Call.Return(run)
	return _c
}

// FindByIds provides a mock function with given fields: productId, userId
func (_m *MockRepository) FindByIds(productId uint64, userId uint64) (*model.Price, error) {
	ret := _m.Called(productId, userId)

	if len(ret) == 0 {
		panic("no return value specified for FindByIds")
	}

	var r0 *model.Price
	var r1 error
	if rf, ok := ret.Get(0).(func(uint64, uint64) (*model.Price, error)); ok {
		return rf(productId, userId)
	}
	if rf, ok := ret.Get(0).(func(uint64, uint64) *model.Price); ok {
		r0 = rf(productId, userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Price)
		}
	}

	if rf, ok := ret.Get(1).(func(uint64, uint64) error); ok {
		r1 = rf(productId, userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_FindByIds_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByIds'
type MockRepository_FindByIds_Call struct {
	*mock.Call
}

// FindByIds is a helper method to define mock.On call
//   - productId uint64
//   - userId uint64
func (_e *MockRepository_Expecter) FindByIds(productId interface{}, userId interface{}) *MockRepository_FindByIds_Call {
	return &MockRepository_FindByIds_Call{Call: _e.mock.On("FindByIds", productId, userId)}
}

func (_c *MockRepository_FindByIds_Call) Run(run func(productId uint64, userId uint64)) *MockRepository_FindByIds_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint64), args[1].(uint64))
	})
	return _c
}

func (_c *MockRepository_FindByIds_Call) Return(_a0 *model.Price, _a1 error) *MockRepository_FindByIds_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_FindByIds_Call) RunAndReturn(run func(uint64, uint64) (*model.Price, error)) *MockRepository_FindByIds_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: _a0
func (_m *MockRepository) Update(_a0 *model.Price) (*model.Price, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *model.Price
	var r1 error
	if rf, ok := ret.Get(0).(func(*model.Price) (*model.Price, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(*model.Price) *model.Price); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Price)
		}
	}

	if rf, ok := ret.Get(1).(func(*model.Price) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - _a0 *model.Price
func (_e *MockRepository_Expecter) Update(_a0 interface{}) *MockRepository_Update_Call {
	return &MockRepository_Update_Call{Call: _e.mock.On("Update", _a0)}
}

func (_c *MockRepository_Update_Call) Run(run func(_a0 *model.Price)) *MockRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*model.Price))
	})
	return _c
}

func (_c *MockRepository_Update_Call) Return(_a0 *model.Price, _a1 error) *MockRepository_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_Update_Call) RunAndReturn(run func(*model.Price) (*model.Price, error)) *MockRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
