// Code generated by MockGen. DO NOT EDIT.
// Source: user-service-client/repository.go
//
// Generated by this command:
//
//	mockgen.exe -source=user-service-client/repository.go -package=user_service_client_mocks -destination=_mocks/user-service-client/repository.go
//
// Package user_service_client_mocks is a generated GoMock package.
package user_service_client_mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// MoveBalance mocks base method.
func (m *MockRepository) MoveBalance(userId, receivingUserId uint64, amount int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MoveBalance", userId, receivingUserId, amount)
	ret0, _ := ret[0].(error)
	return ret0
}

// MoveBalance indicates an expected call of MoveBalance.
func (mr *MockRepositoryMockRecorder) MoveBalance(userId, receivingUserId, amount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MoveBalance", reflect.TypeOf((*MockRepository)(nil).MoveBalance), userId, receivingUserId, amount)
}
