// Code generated by mockery v2.39.1. DO NOT EDIT.

package userShoppingList

import (
	mock "github.com/stretchr/testify/mock"
	model "hsfl.de/group6/hsfl-master-ai-cloud-engineering/shoppinglist-service/userShoppingList/model"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: _a0
func (_m *MockRepository) Create(_a0 *model.UserShoppingList) (*model.UserShoppingList, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *model.UserShoppingList
	var r1 error
	if rf, ok := ret.Get(0).(func(*model.UserShoppingList) (*model.UserShoppingList, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(*model.UserShoppingList) *model.UserShoppingList); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.UserShoppingList)
		}
	}

	if rf, ok := ret.Get(1).(func(*model.UserShoppingList) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - _a0 *model.UserShoppingList
func (_e *MockRepository_Expecter) Create(_a0 interface{}) *MockRepository_Create_Call {
	return &MockRepository_Create_Call{Call: _e.mock.On("Create", _a0)}
}

func (_c *MockRepository_Create_Call) Run(run func(_a0 *model.UserShoppingList)) *MockRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*model.UserShoppingList))
	})
	return _c
}

func (_c *MockRepository_Create_Call) Return(_a0 *model.UserShoppingList, _a1 error) *MockRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_Create_Call) RunAndReturn(run func(*model.UserShoppingList) (*model.UserShoppingList, error)) *MockRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: _a0
func (_m *MockRepository) Delete(_a0 *model.UserShoppingList) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*model.UserShoppingList) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - _a0 *model.UserShoppingList
func (_e *MockRepository_Expecter) Delete(_a0 interface{}) *MockRepository_Delete_Call {
	return &MockRepository_Delete_Call{Call: _e.mock.On("Delete", _a0)}
}

func (_c *MockRepository_Delete_Call) Run(run func(_a0 *model.UserShoppingList)) *MockRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*model.UserShoppingList))
	})
	return _c
}

func (_c *MockRepository_Delete_Call) Return(_a0 error) *MockRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_Delete_Call) RunAndReturn(run func(*model.UserShoppingList) error) *MockRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindAllById provides a mock function with given fields: userId
func (_m *MockRepository) FindAllById(userId uint64) ([]*model.UserShoppingList, error) {
	ret := _m.Called(userId)

	if len(ret) == 0 {
		panic("no return value specified for FindAllById")
	}

	var r0 []*model.UserShoppingList
	var r1 error
	if rf, ok := ret.Get(0).(func(uint64) ([]*model.UserShoppingList, error)); ok {
		return rf(userId)
	}
	if rf, ok := ret.Get(0).(func(uint64) []*model.UserShoppingList); ok {
		r0 = rf(userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.UserShoppingList)
		}
	}

	if rf, ok := ret.Get(1).(func(uint64) error); ok {
		r1 = rf(userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_FindAllById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAllById'
type MockRepository_FindAllById_Call struct {
	*mock.Call
}

// FindAllById is a helper method to define mock.On call
//   - userId uint64
func (_e *MockRepository_Expecter) FindAllById(userId interface{}) *MockRepository_FindAllById_Call {
	return &MockRepository_FindAllById_Call{Call: _e.mock.On("FindAllById", userId)}
}

func (_c *MockRepository_FindAllById_Call) Run(run func(userId uint64)) *MockRepository_FindAllById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint64))
	})
	return _c
}

func (_c *MockRepository_FindAllById_Call) Return(_a0 []*model.UserShoppingList, _a1 error) *MockRepository_FindAllById_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_FindAllById_Call) RunAndReturn(run func(uint64) ([]*model.UserShoppingList, error)) *MockRepository_FindAllById_Call {
	_c.Call.Return(run)
	return _c
}

// FindById provides a mock function with given fields: listId
func (_m *MockRepository) FindById(listId uint64) (*model.UserShoppingList, error) {
	ret := _m.Called(listId)

	if len(ret) == 0 {
		panic("no return value specified for FindById")
	}

	var r0 *model.UserShoppingList
	var r1 error
	if rf, ok := ret.Get(0).(func(uint64) (*model.UserShoppingList, error)); ok {
		return rf(listId)
	}
	if rf, ok := ret.Get(0).(func(uint64) *model.UserShoppingList); ok {
		r0 = rf(listId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.UserShoppingList)
		}
	}

	if rf, ok := ret.Get(1).(func(uint64) error); ok {
		r1 = rf(listId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_FindById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindById'
type MockRepository_FindById_Call struct {
	*mock.Call
}

// FindById is a helper method to define mock.On call
//   - listId uint64
func (_e *MockRepository_Expecter) FindById(listId interface{}) *MockRepository_FindById_Call {
	return &MockRepository_FindById_Call{Call: _e.mock.On("FindById", listId)}
}

func (_c *MockRepository_FindById_Call) Run(run func(listId uint64)) *MockRepository_FindById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint64))
	})
	return _c
}

func (_c *MockRepository_FindById_Call) Return(_a0 *model.UserShoppingList, _a1 error) *MockRepository_FindById_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_FindById_Call) RunAndReturn(run func(uint64) (*model.UserShoppingList, error)) *MockRepository_FindById_Call {
	_c.Call.Return(run)
	return _c
}

// FindByIds provides a mock function with given fields: userId, listId
func (_m *MockRepository) FindByIds(userId uint64, listId uint64) (*model.UserShoppingList, error) {
	ret := _m.Called(userId, listId)

	if len(ret) == 0 {
		panic("no return value specified for FindByIds")
	}

	var r0 *model.UserShoppingList
	var r1 error
	if rf, ok := ret.Get(0).(func(uint64, uint64) (*model.UserShoppingList, error)); ok {
		return rf(userId, listId)
	}
	if rf, ok := ret.Get(0).(func(uint64, uint64) *model.UserShoppingList); ok {
		r0 = rf(userId, listId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.UserShoppingList)
		}
	}

	if rf, ok := ret.Get(1).(func(uint64, uint64) error); ok {
		r1 = rf(userId, listId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_FindByIds_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByIds'
type MockRepository_FindByIds_Call struct {
	*mock.Call
}

// FindByIds is a helper method to define mock.On call
//   - userId uint64
//   - listId uint64
func (_e *MockRepository_Expecter) FindByIds(userId interface{}, listId interface{}) *MockRepository_FindByIds_Call {
	return &MockRepository_FindByIds_Call{Call: _e.mock.On("FindByIds", userId, listId)}
}

func (_c *MockRepository_FindByIds_Call) Run(run func(userId uint64, listId uint64)) *MockRepository_FindByIds_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint64), args[1].(uint64))
	})
	return _c
}

func (_c *MockRepository_FindByIds_Call) Return(_a0 *model.UserShoppingList, _a1 error) *MockRepository_FindByIds_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_FindByIds_Call) RunAndReturn(run func(uint64, uint64) (*model.UserShoppingList, error)) *MockRepository_FindByIds_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: list
func (_m *MockRepository) Update(list *model.UserShoppingList) (*model.UserShoppingList, error) {
	ret := _m.Called(list)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *model.UserShoppingList
	var r1 error
	if rf, ok := ret.Get(0).(func(*model.UserShoppingList) (*model.UserShoppingList, error)); ok {
		return rf(list)
	}
	if rf, ok := ret.Get(0).(func(*model.UserShoppingList) *model.UserShoppingList); ok {
		r0 = rf(list)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.UserShoppingList)
		}
	}

	if rf, ok := ret.Get(1).(func(*model.UserShoppingList) error); ok {
		r1 = rf(list)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - list *model.UserShoppingList
func (_e *MockRepository_Expecter) Update(list interface{}) *MockRepository_Update_Call {
	return &MockRepository_Update_Call{Call: _e.mock.On("Update", list)}
}

func (_c *MockRepository_Update_Call) Run(run func(list *model.UserShoppingList)) *MockRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*model.UserShoppingList))
	})
	return _c
}

func (_c *MockRepository_Update_Call) Return(_a0 *model.UserShoppingList, _a1 error) *MockRepository_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_Update_Call) RunAndReturn(run func(*model.UserShoppingList) (*model.UserShoppingList, error)) *MockRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
