// Code generated by protoc-gen-go. DO NOT EDIT.
// source: bulletin-board.proto

package bulletin_board

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Feed struct {
	Posts                []*Post  `protobuf:"bytes,1,rep,name=posts,proto3" json:"posts,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Feed) Reset()         { *m = Feed{} }
func (m *Feed) String() string { return proto.CompactTextString(m) }
func (*Feed) ProtoMessage()    {}
func (*Feed) Descriptor() ([]byte, []int) {
	return fileDescriptor_82c01485c53a59d7, []int{0}
}

func (m *Feed) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Feed.Unmarshal(m, b)
}
func (m *Feed) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Feed.Marshal(b, m, deterministic)
}
func (m *Feed) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Feed.Merge(m, src)
}
func (m *Feed) XXX_Size() int {
	return xxx_messageInfo_Feed.Size(m)
}
func (m *Feed) XXX_DiscardUnknown() {
	xxx_messageInfo_Feed.DiscardUnknown(m)
}

var xxx_messageInfo_Feed proto.InternalMessageInfo

func (m *Feed) GetPosts() []*Post {
	if m != nil {
		return m.Posts
	}
	return nil
}

type Post struct {
	ID                   uint64               `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,3,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`
	DeletedAt            *timestamp.Timestamp `protobuf:"bytes,4,opt,name=DeletedAt,proto3" json:"DeletedAt,omitempty"`
	Title                string               `protobuf:"bytes,5,opt,name=Title,proto3" json:"Title,omitempty"`
	Content              string               `protobuf:"bytes,6,opt,name=Content,proto3" json:"Content,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Post) Reset()         { *m = Post{} }
func (m *Post) String() string { return proto.CompactTextString(m) }
func (*Post) ProtoMessage()    {}
func (*Post) Descriptor() ([]byte, []int) {
	return fileDescriptor_82c01485c53a59d7, []int{1}
}

func (m *Post) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Post.Unmarshal(m, b)
}
func (m *Post) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Post.Marshal(b, m, deterministic)
}
func (m *Post) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Post.Merge(m, src)
}
func (m *Post) XXX_Size() int {
	return xxx_messageInfo_Post.Size(m)
}
func (m *Post) XXX_DiscardUnknown() {
	xxx_messageInfo_Post.DiscardUnknown(m)
}

var xxx_messageInfo_Post proto.InternalMessageInfo

func (m *Post) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Post) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Post) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *Post) GetDeletedAt() *timestamp.Timestamp {
	if m != nil {
		return m.DeletedAt
	}
	return nil
}

func (m *Post) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Post) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type Request struct {
	Amount               uint64   `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_82c01485c53a59d7, []int{2}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func init() {
	proto.RegisterType((*Feed)(nil), "bulletin_board.Feed")
	proto.RegisterType((*Post)(nil), "bulletin_board.Post")
	proto.RegisterType((*Request)(nil), "bulletin_board.Request")
}

func init() { proto.RegisterFile("bulletin-board.proto", fileDescriptor_82c01485c53a59d7) }

var fileDescriptor_82c01485c53a59d7 = []byte{
	// 303 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x91, 0xcf, 0x4b, 0xfb, 0x40,
	0x10, 0xc5, 0xd9, 0x36, 0x6d, 0xbf, 0x9d, 0x42, 0x0f, 0x4b, 0xe8, 0x77, 0xe9, 0xc5, 0xd8, 0x53,
	0x10, 0xdc, 0x40, 0xbc, 0xe8, 0xd1, 0xb6, 0x08, 0xbd, 0x69, 0xac, 0x17, 0x2f, 0x92, 0x34, 0x63,
	0x08, 0x24, 0xd9, 0x98, 0x9d, 0xf8, 0x97, 0xfb, 0x07, 0xc8, 0xe6, 0x47, 0xa5, 0x7a, 0xe8, 0xf1,
	0xcd, 0xbe, 0xcf, 0xf0, 0xe6, 0x2d, 0xd8, 0x51, 0x9d, 0x65, 0x48, 0x69, 0x71, 0x1d, 0xa9, 0xb0,
	0x8a, 0x65, 0x59, 0x29, 0x52, 0x7c, 0xde, 0x4f, 0xdf, 0x9a, 0xe9, 0xf2, 0x22, 0x51, 0x2a, 0xc9,
	0xd0, 0x6b, 0x5e, 0xa3, 0xfa, 0xdd, 0xa3, 0x34, 0x47, 0x4d, 0x61, 0x5e, 0xb6, 0xc0, 0xca, 0x07,
	0xeb, 0x01, 0x31, 0xe6, 0x57, 0x30, 0x2a, 0x95, 0x26, 0x2d, 0x98, 0x33, 0x74, 0x67, 0xbe, 0x2d,
	0x4f, 0x17, 0xc9, 0x47, 0xa5, 0x29, 0x68, 0x2d, 0xab, 0x2f, 0x06, 0x96, 0xd1, 0x7c, 0x0e, 0x83,
	0xdd, 0x56, 0x30, 0x87, 0xb9, 0x56, 0x30, 0xd8, 0x6d, 0xf9, 0x2d, 0x4c, 0x37, 0x15, 0x86, 0x84,
	0xf1, 0x3d, 0x89, 0x81, 0xc3, 0xdc, 0x99, 0xbf, 0x94, 0x6d, 0x02, 0xd9, 0x27, 0x90, 0xfb, 0x3e,
	0x41, 0xf0, 0x63, 0x36, 0xe4, 0x4b, 0x19, 0x77, 0xe4, 0xf0, 0x3c, 0x79, 0x34, 0x1b, 0x72, 0x8b,
	0x19, 0xb6, 0xa4, 0x75, 0x9e, 0x3c, 0x9a, 0xb9, 0x0d, 0xa3, 0x7d, 0x4a, 0x19, 0x8a, 0x91, 0xc3,
	0xdc, 0x69, 0xd0, 0x0a, 0x2e, 0x60, 0xb2, 0x51, 0x05, 0x61, 0x41, 0x62, 0xdc, 0xcc, 0x7b, 0xb9,
	0xba, 0x84, 0x49, 0x80, 0x1f, 0x35, 0x6a, 0xe2, 0x0b, 0x18, 0x87, 0xb9, 0xaa, 0x0b, 0xea, 0x8e,
	0xef, 0x94, 0xff, 0x04, 0xf6, 0xba, 0xeb, 0x6d, 0x6d, 0x6a, 0x7b, 0xc6, 0xea, 0x33, 0x3d, 0x20,
	0xbf, 0x83, 0x7f, 0x09, 0x92, 0xe9, 0x4c, 0xf3, 0xff, 0xbf, 0xab, 0xed, 0x96, 0x2e, 0xff, 0x74,
	0x6e, 0x3e, 0x66, 0xbd, 0x78, 0xb5, 0xa5, 0x57, 0x95, 0x07, 0xef, 0xf4, 0x31, 0x1a, 0x37, 0xc7,
	0xdd, 0x7c, 0x07, 0x00, 0x00, 0xff, 0xff, 0xbb, 0x72, 0xc5, 0x14, 0x08, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BulletinBoardServiceClient is the client API for BulletinBoardService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BulletinBoardServiceClient interface {
	GetPosts(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Feed, error)
}

type bulletinBoardServiceClient struct {
	cc *grpc.ClientConn
}

func NewBulletinBoardServiceClient(cc *grpc.ClientConn) BulletinBoardServiceClient {
	return &bulletinBoardServiceClient{cc}
}

func (c *bulletinBoardServiceClient) GetPosts(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Feed, error) {
	out := new(Feed)
	err := c.cc.Invoke(ctx, "/bulletin_board.BulletinBoardService/getPosts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BulletinBoardServiceServer is the server API for BulletinBoardService service.
type BulletinBoardServiceServer interface {
	GetPosts(context.Context, *Request) (*Feed, error)
}

// UnimplementedBulletinBoardServiceServer can be embedded to have forward compatible implementations.
type UnimplementedBulletinBoardServiceServer struct {
}

func (*UnimplementedBulletinBoardServiceServer) GetPosts(ctx context.Context, req *Request) (*Feed, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPosts not implemented")
}

func RegisterBulletinBoardServiceServer(s *grpc.Server, srv BulletinBoardServiceServer) {
	s.RegisterService(&_BulletinBoardService_serviceDesc, srv)
}

func _BulletinBoardService_GetPosts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BulletinBoardServiceServer).GetPosts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bulletin_board.BulletinBoardService/GetPosts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BulletinBoardServiceServer).GetPosts(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _BulletinBoardService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "bulletin_board.BulletinBoardService",
	HandlerType: (*BulletinBoardServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getPosts",
			Handler:    _BulletinBoardService_GetPosts_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bulletin-board.proto",
}
