// Code generated by MockGen. DO NOT EDIT.
// Source: transactions/controller.go
//
// Generated by this command:
//
//	mockgen.exe -source=transactions/controller.go -package=mocks -destination=_mocks/controller.go
//
// Package mocks is a generated GoMock package.
package mocks

import (
	http "net/http"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockController is a mock of Controller interface.
type MockController struct {
	ctrl     *gomock.Controller
	recorder *MockControllerMockRecorder
}

// MockControllerMockRecorder is the mock recorder for MockController.
type MockControllerMockRecorder struct {
	mock *MockController
}

// NewMockController creates a new mock instance.
func NewMockController(ctrl *gomock.Controller) *MockController {
	mock := &MockController{ctrl: ctrl}
	mock.recorder = &MockControllerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockController) EXPECT() *MockControllerMockRecorder {
	return m.recorder
}

// CreateTransaction mocks base method.
func (m *MockController) CreateTransaction(arg0 http.ResponseWriter, arg1 *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CreateTransaction", arg0, arg1)
}

// CreateTransaction indicates an expected call of CreateTransaction.
func (mr *MockControllerMockRecorder) CreateTransaction(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTransaction", reflect.TypeOf((*MockController)(nil).CreateTransaction), arg0, arg1)
}

// GetYourTransactions mocks base method.
func (m *MockController) GetYourTransactions(arg0 http.ResponseWriter, arg1 *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetYourTransactions", arg0, arg1)
}

// GetYourTransactions indicates an expected call of GetYourTransactions.
func (mr *MockControllerMockRecorder) GetYourTransactions(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetYourTransactions", reflect.TypeOf((*MockController)(nil).GetYourTransactions), arg0, arg1)
}
