// Code generated by mockery v2.39.1. DO NOT EDIT.

package userShoppingListEntry

import (
	mock "github.com/stretchr/testify/mock"
	model "hsfl.de/group6/hsfl-master-ai-cloud-engineering/shoppinglist-service/userShoppingListEntry/model"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: _a0
func (_m *MockRepository) Create(_a0 *model.UserShoppingListEntry) (*model.UserShoppingListEntry, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *model.UserShoppingListEntry
	var r1 error
	if rf, ok := ret.Get(0).(func(*model.UserShoppingListEntry) (*model.UserShoppingListEntry, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(*model.UserShoppingListEntry) *model.UserShoppingListEntry); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.UserShoppingListEntry)
		}
	}

	if rf, ok := ret.Get(1).(func(*model.UserShoppingListEntry) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - _a0 *model.UserShoppingListEntry
func (_e *MockRepository_Expecter) Create(_a0 interface{}) *MockRepository_Create_Call {
	return &MockRepository_Create_Call{Call: _e.mock.On("Create", _a0)}
}

func (_c *MockRepository_Create_Call) Run(run func(_a0 *model.UserShoppingListEntry)) *MockRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*model.UserShoppingListEntry))
	})
	return _c
}

func (_c *MockRepository_Create_Call) Return(_a0 *model.UserShoppingListEntry, _a1 error) *MockRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_Create_Call) RunAndReturn(run func(*model.UserShoppingListEntry) (*model.UserShoppingListEntry, error)) *MockRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: _a0
func (_m *MockRepository) Delete(_a0 *model.UserShoppingListEntry) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*model.UserShoppingListEntry) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - _a0 *model.UserShoppingListEntry
func (_e *MockRepository_Expecter) Delete(_a0 interface{}) *MockRepository_Delete_Call {
	return &MockRepository_Delete_Call{Call: _e.mock.On("Delete", _a0)}
}

func (_c *MockRepository_Delete_Call) Run(run func(_a0 *model.UserShoppingListEntry)) *MockRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*model.UserShoppingListEntry))
	})
	return _c
}

func (_c *MockRepository_Delete_Call) Return(_a0 error) *MockRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_Delete_Call) RunAndReturn(run func(*model.UserShoppingListEntry) error) *MockRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindAll provides a mock function with given fields: shoppingListId
func (_m *MockRepository) FindAll(shoppingListId uint64) ([]*model.UserShoppingListEntry, error) {
	ret := _m.Called(shoppingListId)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []*model.UserShoppingListEntry
	var r1 error
	if rf, ok := ret.Get(0).(func(uint64) ([]*model.UserShoppingListEntry, error)); ok {
		return rf(shoppingListId)
	}
	if rf, ok := ret.Get(0).(func(uint64) []*model.UserShoppingListEntry); ok {
		r0 = rf(shoppingListId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.UserShoppingListEntry)
		}
	}

	if rf, ok := ret.Get(1).(func(uint64) error); ok {
		r1 = rf(shoppingListId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type MockRepository_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
//   - shoppingListId uint64
func (_e *MockRepository_Expecter) FindAll(shoppingListId interface{}) *MockRepository_FindAll_Call {
	return &MockRepository_FindAll_Call{Call: _e.mock.On("FindAll", shoppingListId)}
}

func (_c *MockRepository_FindAll_Call) Run(run func(shoppingListId uint64)) *MockRepository_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint64))
	})
	return _c
}

func (_c *MockRepository_FindAll_Call) Return(_a0 []*model.UserShoppingListEntry, _a1 error) *MockRepository_FindAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_FindAll_Call) RunAndReturn(run func(uint64) ([]*model.UserShoppingListEntry, error)) *MockRepository_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindByIds provides a mock function with given fields: shoppingListId, productId
func (_m *MockRepository) FindByIds(shoppingListId uint64, productId uint64) (*model.UserShoppingListEntry, error) {
	ret := _m.Called(shoppingListId, productId)

	if len(ret) == 0 {
		panic("no return value specified for FindByIds")
	}

	var r0 *model.UserShoppingListEntry
	var r1 error
	if rf, ok := ret.Get(0).(func(uint64, uint64) (*model.UserShoppingListEntry, error)); ok {
		return rf(shoppingListId, productId)
	}
	if rf, ok := ret.Get(0).(func(uint64, uint64) *model.UserShoppingListEntry); ok {
		r0 = rf(shoppingListId, productId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.UserShoppingListEntry)
		}
	}

	if rf, ok := ret.Get(1).(func(uint64, uint64) error); ok {
		r1 = rf(shoppingListId, productId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_FindByIds_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByIds'
type MockRepository_FindByIds_Call struct {
	*mock.Call
}

// FindByIds is a helper method to define mock.On call
//   - shoppingListId uint64
//   - productId uint64
func (_e *MockRepository_Expecter) FindByIds(shoppingListId interface{}, productId interface{}) *MockRepository_FindByIds_Call {
	return &MockRepository_FindByIds_Call{Call: _e.mock.On("FindByIds", shoppingListId, productId)}
}

func (_c *MockRepository_FindByIds_Call) Run(run func(shoppingListId uint64, productId uint64)) *MockRepository_FindByIds_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint64), args[1].(uint64))
	})
	return _c
}

func (_c *MockRepository_FindByIds_Call) Return(_a0 *model.UserShoppingListEntry, _a1 error) *MockRepository_FindByIds_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_FindByIds_Call) RunAndReturn(run func(uint64, uint64) (*model.UserShoppingListEntry, error)) *MockRepository_FindByIds_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: list
func (_m *MockRepository) Update(list *model.UserShoppingListEntry) (*model.UserShoppingListEntry, error) {
	ret := _m.Called(list)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *model.UserShoppingListEntry
	var r1 error
	if rf, ok := ret.Get(0).(func(*model.UserShoppingListEntry) (*model.UserShoppingListEntry, error)); ok {
		return rf(list)
	}
	if rf, ok := ret.Get(0).(func(*model.UserShoppingListEntry) *model.UserShoppingListEntry); ok {
		r0 = rf(list)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.UserShoppingListEntry)
		}
	}

	if rf, ok := ret.Get(1).(func(*model.UserShoppingListEntry) error); ok {
		r1 = rf(list)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - list *model.UserShoppingListEntry
func (_e *MockRepository_Expecter) Update(list interface{}) *MockRepository_Update_Call {
	return &MockRepository_Update_Call{Call: _e.mock.On("Update", list)}
}

func (_c *MockRepository_Update_Call) Run(run func(list *model.UserShoppingListEntry)) *MockRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*model.UserShoppingListEntry))
	})
	return _c
}

func (_c *MockRepository_Update_Call) Return(_a0 *model.UserShoppingListEntry, _a1 error) *MockRepository_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_Update_Call) RunAndReturn(run func(*model.UserShoppingListEntry) (*model.UserShoppingListEntry, error)) *MockRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
